### ISSUE TITLE
Image ID doesn't override as expected

### ISSUE THREAD

**Issue by rchenzheng** [clouddrove/terraform-digitalocean-droplet#12]
As seen in https://github.com/clouddrove/terraform-digitalocean-droplet/blob/master/main.tf#L60 it will always pull the official image, if the upstream slug updates then it'll force a replacement(**Ask me how I know**)

It should instead coalesce on `var.image_id` (which is defined but not used)

I'll handle this issue myself as I've fixed this issue in my local fork.

**Comment by vibhutigoyal** [comment]
Hey @rchenzheng The issue has been fixed and tested successfully.
